chore(lwc): add typings
salesforce/lwc pull request #2067
Opened 2020-10-23 15:10 UTC by TwoPlusTwoOne

- querySelector
- querySelectorAll
- createElement

these methods are used and available but no typings are currently available

## Details
Adding types to the lwc package typings

## Does this PR introduce breaking changes?

* ✅ `No, it does not introduce breaking changes.`

If yes, please describe the impact and migration path for existing applications.

## The PR fulfills these requirements:
* Have tests for the proposed changes been added? ❌ (N/A)
* Have you followed [these instructions](../CONTRIBUTING.md#-commit-message-conventions) to clearly describe the issue being fixed or feature enhanced? ✅ 

## GUS work item
N/A

2020-10-26 11:00 UTC, pmdartus requested changes
The `querySelector` and `querySelectorAll` types look good to me, I would remove `createElement` for now (see comments for more details).

2020-10-26 17:18 UTC, TwoPlusTwoOne commented on packages/lwc/types.d.ts
> +    export function createElement(
So for tests, the idea would be to use normal `document.createElement` in the future?

2020-10-28 10:30 UTC, pmdartus commented on packages/lwc/types.d.ts
> +    export function createElement(
We are still not yet there, but it's the idea in the long run.

2020-10-28 13:07 UTC, TwoPlusTwoOne commented on packages/lwc/types.d.ts
> +    export function createElement(
Done :)

2020-10-30 08:54 UTC, pmdartus approved these changes

2020-10-30 08:58 UTC, pmdartus approved these changes

2020-10-30 08:59 UTC, merged