test(integration-karma): add integration tests for EventTarget
salesforce/lwc pull request #2141
Opened 2020-12-23 12:25 UTC by abdulsattar

## Details
addEventListener, removeEventListener, dispatchEvent

Co-Authored-By: Sumit Jaiswal <jaiswal.sumit35@gmail.com>

## Does this PR introduce breaking changes?

* ✅ `No, it does not introduce breaking changes.`

## The PR fulfills these requirements:
* Have tests for the proposed changes been added? ✅
* Have you followed [these instructions](../CONTRIBUTING.md#-commit-message-conventions) to clearly describe the issue being fixed or feature enhanced? ✅

## GUS work item
W-8597107

2020-12-23 13:18 UTC, ekashida requested changes

2020-12-23 13:18 UTC, ekashida commented on packages/integration-karma/test/shadow-dom/EventTarget-methods/EventTarget.addEventListener.spec.js
> +        it('should throw error when a listener config is passed for shadow root and host', () => {
This is probably the only test that shouldn't run in native shadow mode.

2020-12-23 13:18 UTC, ekashida commented on packages/integration-karma/test/shadow-dom/EventTarget-methods/EventTarget.dispatchEvent.spec.js
> +if (!process.env.NATIVE_SHADOW) {
These tests should be fine running in native shadow mode.

2020-12-23 13:18 UTC, ekashida commented on packages/integration-karma/test/shadow-dom/EventTarget-methods/EventTarget.removeEventListener.spec.js
> +if (!process.env.NATIVE_SHADOW) {
These tests should be fine running in native shadow mode.

2020-12-23 14:19 UTC, ravijayaramappa commented
@abdulsattar We have disabled integration test suites for forks(to protect sauce labs account information). Please close this PR, push your feature branch to the lwc repo directly and create a new PR.

2020-12-23 17:28 UTC, abdulsattar commented
@ravijayaramappa we don't have write access to this repo. @ekashida can you please grant us write access, we'll create a feature branch to push.

2020-12-24 07:10 UTC, Sumitjg commented
@ravijayaramappa shall I update lwc/CONTRIBUTING doc not to use fork repo in the steps mentioned for submitting a pull request ?

2020-12-24 07:23 UTC, closed without merging