refactor(babel-plugin-component): move component registration transform out of post-process
salesforce/lwc pull request #2221
Opened 2021-02-01 18:47 UTC by ekashida

## Details

Move component registration transform out of post-process.

## Does this PR introduce breaking changes?

* ✅ `No, it does not introduce breaking changes.`

## GUS work item

W-8630713

2021-02-02 10:02 UTC, pmdartus requested changes

2021-02-10 16:29 UTC, ekashida commented on packages/@lwc/babel-plugin-component/src/component.js
> +    const { filename } = opts;
Based on the fact that we provide a fake file name [here](https://github.com/salesforce/lwc/blob/master/packages/@lwc/babel-plugin-component/src/__tests__/utils/test-transform.js#L11), I would guess not.

2021-02-17 03:56 UTC, ekashida commented
@pmdartus this one is ready for another pass

2021-02-17 08:51 UTC, pmdartus approved these changes

2021-02-17 08:51 UTC, merged