chore: weekly dependencies update
salesforce/lwc pull request #2251
Opened 2021-02-19 00:23 UTC by ravijayaramappa

## Details
Also addressed security vulnerability GHSA-2m8v-572m-ff2v via manual resolution.
Issue filed for best repo salesforce/best#263 to address this dependency.

## Does this PR introduce breaking changes?

* ✅ `No, it does not introduce breaking changes.`

If yes, please describe the impact and migration path for existing applications.

## The PR fulfills these requirements:
* Have tests for the proposed changes been added? ❌
* Have you followed [these instructions](../CONTRIBUTING.md#-commit-message-conventions) to clearly describe the issue being fixed or feature enhanced? ✅ 

## GUS work item
@W-7258582

2021-02-19 08:40 UTC, pmdartus requested changes

2021-02-19 08:40 UTC, pmdartus commented on package.json
> +    "@babel/core": "^7.12.17",
All the babel-related updates should be reverted for now. The latest version of Babel breaks the transform.
@ekashida is actively working on this.

2021-02-22 09:06 UTC, pmdartus approved these changes

2021-02-22 17:33 UTC, ekashida approved these changes

2021-02-22 18:17 UTC, merged