fix(synthetic-shadow): synthetic shadow doesn't preserve assignedSlot behavior
salesforce/lwc pull request #2547
Opened 2021-10-22 23:45 UTC by rui-rayqiu

## Details
Fixes #2377 

When synthetic shadow polyfill is loaded, accessing `assignedSlot` for elements that are assigned to slots inside native shadow components will return null. The proposed fix is to call the native `assignedSlot` getter under this condition.

## Does this pull request introduce a breaking change?

* ✅ No, it does not introduce a breaking change.

## Does this pull request introduce an observable change?

* ✅ No, it does not introduce an observable change.

## GUS work item

W-9492998

2021-11-06 16:19 UTC, ekashida requested changes
I'm not sure this is the right logic, I think we want something more like this:
```
const nodeOwnerKey = getNodeOwnerKey(this);
const isSyntheticShadowed = !isUndefined(nodeOwnerKey);
if (isSyntheticShadowed) {
    // existing logic for synthetic goes here
} else {
    if (this instanceof Element) {
        return originalElementAssignedSlotGetter.call(this); 
    }
    if (this instanceof Text) {
        return originalTextAssignedSlotGetter.call(this);
    }
}

return null;
```

Could you also make sure we have sufficient test coverage for this? At the least, we should have the following test cases:

- default slotted content should return `null` for `assignedSlot` for light, synthetic, and native (see what current behavior is for synthetic before making changes since it might be breaking)
- `assignedSlot` should return the expected slot for light, synthetic, and native

2021-11-11 19:26 UTC, rui-rayqiu commented on packages/@lwc/synthetic-shadow/src/faux-shadow/slot.ts
> +                return originalTextAssignedSlotGetter.call(this);
@ekashida I see [here](https://github.com/salesforce/lwc/blob/d93e2963d8d32b138ce9ed130d98e7bef84b3d74/packages/%40lwc/synthetic-shadow/src/faux-shadow/text.ts#L15) that we put the same function for Text node so it should be reachable. We have a test [here](https://github.com/salesforce/lwc/blob/30ca15d645c88e232905d782ac1163f489a596a8/packages/integration-karma/test/shadow-dom/Element-properties/Element.assignedSlot.spec.js#L63) for slotted text node.

2021-11-11 20:57 UTC, rui-rayqiu commented
> isSyntheticShadowed



> I'm not sure this is the right logic, I think we want something more like this:
> 
> ```
> const nodeOwnerKey = getNodeOwnerKey(this);
> const isSyntheticShadowed = !isUndefined(nodeOwnerKey);
> if (isSyntheticShadowed) {
>     // existing logic for synthetic goes here
> } else {
>     if (this instanceof Element) {
>         return originalElementAssignedSlotGetter.call(this); 
>     }
>     if (this instanceof Text) {
>         return originalTextAssignedSlotGetter.call(this);
>     }
> }
> 
> return null;
> ```
> 
> Could you also make sure we have sufficient test coverage for this? At the least, we should have the following test cases:
> 
> * default slotted content should return `null` for `assignedSlot` for light, synthetic, and native (see what current behavior is for synthetic before making changes since it might be breaking)
> * `assignedSlot` should return the expected slot for light, synthetic, and native

2021-11-11 21:12 UTC, rui-rayqiu commented
> I'm not sure this is the right logic, I think we want something more like this:
> 
> ```
> const nodeOwnerKey = getNodeOwnerKey(this);
> const isSyntheticShadowed = !isUndefined(nodeOwnerKey);
> if (isSyntheticShadowed) {
>     // existing logic for synthetic goes here
> } else {
>     if (this instanceof Element) {
>         return originalElementAssignedSlotGetter.call(this); 
>     }
>     if (this instanceof Text) {
>         return originalTextAssignedSlotGetter.call(this);
>     }
> }
> 
> return null;
> ```
> 
> Could you also make sure we have sufficient test coverage for this? At the least, we should have the following test cases:
> 
> * default slotted content should return `null` for `assignedSlot` for light, synthetic, and native (see what current behavior is for synthetic before making changes since it might be breaking)
> * `assignedSlot` should return the expected slot for light, synthetic, and native

@ekashida I tried this logic but it does not work for light dom container. If the slotted content is a light DOM node, it doesn't have an owner key so `getNodeOwnerKey` will return undefined for this case too. Is there a suggested way to distinguish this case?

2021-11-12 22:18 UTC, ekashida commented on packages/@lwc/synthetic-shadow/src/faux-shadow/slot.ts
> +                return originalTextAssignedSlotGetter.call(this);
I see, we are checking to see if the parent is an instance of `Element` and not the element itself.

2021-11-12 22:19 UTC, ekashida commented on packages/@lwc/synthetic-shadow/src/faux-shadow/slot.ts
> +        if (sr && isInstanceOfNativeShadowRoot(sr)) {
`isInstanceOfNativeShadowRoot` can handle `null` so we don't need the extra check.
```suggestion
        if (isInstanceOfNativeShadowRoot(sr)) {
```

2021-11-17 18:54 UTC, rui-rayqiu commented on packages/@lwc/synthetic-shadow/src/faux-shadow/slot.ts
> +        const sr = parentNode.shadowRoot;
@ekashida How do we use `shadowRootGetter` here? It seems that `shadowRootGetterPatched` is already patched on `Element.shadowRoot` [here](https://github.com/salesforce/lwc/blob/0de7ef2685fd26f0ba7d56987c8562a880922fe8/packages/%40lwc/synthetic-shadow/src/faux-shadow/element.ts#L169) so using dot-notation will be calling `shadowRootGetterPatched`. Maybe I'm missing something?

2021-11-18 16:18 UTC, ekashida commented on packages/@lwc/synthetic-shadow/src/faux-shadow/slot.ts
> +        const sr = parentNode.shadowRoot;
```
import { shadowRootGetter } from '../env/element';

...

if (parentNode instanceof Element) {
    const sr = shadowRootGetter.call(parentNode);
    if (isInstanceOfNativeShadowRoot(sr)) {
        ...
    }
}

2021-11-22 20:16 UTC, rui-rayqiu commented on packages/@lwc/synthetic-shadow/src/faux-shadow/slot.ts
> +        const sr = parentNode.shadowRoot;
I see. That makes sense. Revised accordingly. Thanks!

2021-11-22 20:30 UTC, rui-rayqiu commented on packages/@lwc/synthetic-shadow/src/faux-shadow/slot.ts
> +        const sr = parentNode.shadowRoot;
I think we have basic test coverage for [assignedSlot](https://github.com/salesforce/lwc/blob/master/packages/integration-karma/test/shadow-dom/Element-properties/Element.assignedSlot.spec.js) and for [light dom](https://github.com/salesforce/lwc/blob/ba58615566edc465b96b7c71eef0f6fb47e15b0f/packages/integration-karma/test/light-dom/synthetic-shadow/index.spec.js#L21). I've also did some manual tests on default slot content returning `null` for `assignedSlot`.

2021-11-23 16:52 UTC, ekashida commented on packages/@lwc/synthetic-shadow/src/faux-shadow/slot.ts
> +        const sr = parentNode.shadowRoot;
> I've also did some manual tests on default slot content returning null for assignedSlot.

Would be great to add the missing coverage for this.

2021-11-23 16:54 UTC, ekashida commented
The failing FF test should be fixed after a rebase.

2021-12-17 23:26 UTC, ekashida approved these changes

2021-12-18 01:14 UTC, merged