feat: ensure tests run before commits
salesforce/lwc pull request #3750
Opened 2023-09-28 19:50 UTC by AllanOricil

## Details

This mitigates the introduction of broken commits.

## Does this pull request introduce a breaking change?

* ✅ No, it does not introduce a breaking change.

## Does this pull request introduce an observable change?

* ✅ No, it does not introduce an observable change.

## GUS work item

N/A

2023-09-28 20:27 UTC, nolanlawson requested changes
Thanks for the PR, but I'm not really a big fan of this approach. The Jest/Karma tests take up to a minute to run (depending on how fast your machine is), and IME that really slows down velocity during development.

On top of that, if you _really_ want to know whether your commit will pass CI, there are about a dozen different modes it has to run in (see [the circleci config](https://github.com/salesforce/lwc/blob/177eb5604086a5cce9eed31c8a5b10a088121c24/.circleci/config.yml#L285-L320)), plus the WebDriverIO tests, tests against various browsers, ad-hoc scripts that check for things like license headers... running just Jest/Karma is a false sense of security.

Right now `lint-staged` does the bare minimum of making sure everything is ESLint formatted and Prettier formatted. I think that's enough for the time being. I've worked on projects where it runs all the unit tests on every commit, and I find that I type `-n` every time, which nullifies the value of the check.

2023-09-28 21:18 UTC, nolanlawson commented on package.json
> +        "test:karma": "nx test @lwc/integration-karma",
On its own, this is a good change... it's a nice shorthand, and we were being inconsistent before.

2023-09-28 21:18 UTC, AllanOricil commented
most difficult PR of my life 🥹

2023-09-28 21:18 UTC, nolanlawson approved these changes

2023-09-29 05:26 UTC, AllanOricil commented
Non related. I just want to vent out.

I'm really relieved that I started working after the jquery era. Look at this app

https://github.com/node-red/node-red/blob/master/packages/node_modules/%40node-red/editor-client/src/js/red.js


😐

2023-09-29 20:22 UTC, nolanlawson commented
Thank you! ❤️

2023-09-29 20:22 UTC, merged